import type { Metadata } from "next"; import { Container } from "@/components/ui/Container"; import { Calculator, Users, Shield, TrendingUp } from "lucide-react"; import Link from "next/link";
const SITE_NAME = "Rekenhet.nl";
export const metadata: Metadata = { title: `Over ${SITE_NAME} — Gratis Online Calculators`, description: "Rekenhet.nl is een gratis online calculatorplatform voor werk & inkomen, ondernemen, geld & verzekeringen, gezondheid en wiskunde. Altijd up-to-date met de laatste wetgeving." };
export default function OverOnsPage() { return (<Container className="py-8 max-w-3xl"><section><h1 className="text-3xl font-bold text-gray-900 mb-2">Over Rekenhet.nl</h1><p className="text-gray-500 mb-8">Gratis, betrouwbaar en altijd up-to-date</p></section>
<section className="space-y-4 mb-10"><p className="text-gray-600 leading-relaxed">Rekenhet.nl is een online platform met <strong>gratis calculators</strong> voor financiële berekeningen, wiskunde, gezondheid en meer. Onze missie is om complexe berekeningen eenvoudig en toegankelijk te maken voor iedereen.</p><p className="text-gray-600 leading-relaxed">Alle calculators worden <strong>maandelijks bijgewerkt</strong> met de laatste wet- en regelgeving (belastingtarieven, toeslagen, subsidies) zodat je altijd kunt rekenen met actuele cijfers.</p></section>
<div className="grid grid-cols-2 gap-4 mb-10">{[
  { icon: Calculator, title: "30+ Calculators", desc: "Van bruto/netto tot hypotheek, BTW en eenheden omrekenen. Alles gratis." },
  { icon: TrendingUp, title: "Altijd actueel", desc: "Belastingtarieven, toeslagen en subsidies worden maandelijks bijgewerkt." },
  { icon: Users, title: "Voor iedereen", desc: "Of je nu ZZP'er, werknemer, student of ondernemer bent." },
  { icon: Shield, title: "Privacy first", desc: "Geen account nodig. Geen tracking. Je data blijft van jou." },
].map((item) => (<div key={item.title} className="rounded-xl border border-gray-100 bg-white p-4 shadow-sm"><item.icon className="h-5 w-5 text-blue-600 mb-2"/><h3 className="text-sm font-semibold text-gray-900 mb-1">{item.title}</h3><p className="text-xs text-gray-500">{item.desc}</p></div>))}</div>
<section className="mb-10"><h2 className="text-xl font-bold text-gray-900 mb-4">Veelgebruikte calculators</h2><div className="grid grid-cols-2 gap-2">{["bruto-netto-salaris-calculator","btw-calculator","bmi-calculator","maximale-hypotheek","uurtarief-berekenen","annuiteiten-lasten","box3-berekenen","kinderbijslag"].map(s=><Link key={s} href={`/algemeen/${s}`} className="rounded-lg border border-gray-100 bg-gray-50 px-3 py-2 text-xs text-gray-600 hover:bg-blue-50 hover:text-blue-600">{s.replace(/-/g," ")}</Link>)}</div></section>
<section className="rounded-xl bg-blue-50 border border-blue-100 p-6 text-center"><h2 className="text-lg font-bold text-gray-900 mb-2">Vragen of suggesties?</h2><p className="text-sm text-gray-600 mb-4">We horen graag hoe we Rekenhet.nl kunnen verbeteren.</p><Link href="/contact" className="inline-flex items-center gap-1.5 rounded-lg bg-blue-600 px-5 py-2.5 text-sm font-semibold text-white hover:bg-blue-700 transition-colors">Neem contact op</Link></section></Container>);}
