import { Calculator, TrendingUp, PiggyBank, Heart, Percent, Clock, type LucideIcon } from "lucide-react";
import * as calc from "@/lib/calculators/extra-calculators-2";

export interface CalcField {
  key: string;
  label: string;
  type: "number" | "select" | "date";
  default: number | string;
  options?: { value: string; label: string }[];
  min?: number;
  max?: number;
  step?: number;
  suffix?: string;
}

export interface CalcOutput {
  key: string;
  label: string;
  format: "number" | "eur" | "text" | "pct";
  suffix?: string;
  color?: string;
  primary?: boolean;
}

export interface CalcConfig {
  title: string;
  icon: LucideIcon;
  iconBg: string;
  category: string;
  description: string;
  fields: CalcField[];
  outputs: CalcOutput[];
  calc: (vals: Record<string, number | string>) => Record<string, number | string>;
}

const I = { Calculator, TrendingUp, PiggyBank, Heart, Percent, Clock };

// ─── Helper ───────────────────────────────────────────────────
function n(v: Record<string, number | string>, k: string): number {
  return typeof v[k] === "number" ? (v[k] as number) : 0;
}

// ─── ALL 50 CONFIGS ───────────────────────────────────────────

export const calculatorConfigs: Record<string, CalcConfig> = {
  // ── Wiskunde (10) ──
  "worteltrekken": { title: "Worteltrekken", icon: I.Calculator, iconBg: "bg-amber-100 text-amber-600", category: "Wiskunde", description: "Bereken de vierkantswortel en het kwadraat van een getal", fields: [{key:"n",label:"Getal",type:"number",default:16,min:0}], outputs:[{key:"wortel",label:"Vierkantswortel",format:"number",primary:true},{key:"kwadraat",label:"Kwadraat",format:"number"}], calc:v=>(n(v,"n")>=0?calc.worteltrekken(n(v,"n")):{wortel:0,kwadraat:0}) },
  "machtsverheffen": { title: "Machtsverheffen", icon: I.Calculator, iconBg: "bg-amber-100 text-amber-600", category: "Wiskunde", description: "Bereken een grondtal tot een macht", fields:[{key:"basis",label:"Grondtal",type:"number",default:2},{key:"exponent",label:"Exponent",type:"number",default:3}], outputs:[{key:"resultaat",label:"Uitkomst",format:"number",primary:true}], calc:v=>({resultaat:calc.machtsverheffen(n(v,"basis"),n(v,"exponent"))}) },
  "breuk-vereenvoudigen": { title: "Breuk Vereenvoudigen", icon: I.Percent, iconBg: "bg-amber-100 text-amber-600", category: "Wiskunde", description: "Vereenvoudig een breuk naar de kleinst mogelijke teller en noemer", fields:[{key:"teller",label:"Teller",type:"number",default:12},{key:"noemer",label:"Noemer",type:"number",default:8}], outputs:[{key:"teller",label:"Teller",format:"number",primary:true},{key:"noemer",label:"Noemer",format:"number"},{key:"decimaal",label:"Decimale waarde",format:"number"}], calc:v=>calc.breukVereenvoudigen(n(v,"teller"),n(v,"noemer")) },
  "decimaal-naar-breuk": { title: "Decimaal naar Breuk", icon: I.Percent, iconBg: "bg-amber-100 text-amber-600", category: "Wiskunde", description: "Zet een decimaal getal om naar een breuk", fields:[{key:"decimaal",label:"Decimaal getal",type:"number",default:0.75,step:0.01}], outputs:[{key:"teller",label:"Teller",format:"number",primary:true},{key:"noemer",label:"Noemer",format:"number"}], calc:v=>calc.decimaalNaarBreuk(n(v,"decimaal")) },
  "kgv-berekenen": { title: "KGV Berekenen", icon: I.Calculator, iconBg: "bg-amber-100 text-amber-600", category: "Wiskunde", description: "Bereken het kleinste gemene veelvoud van twee getallen", fields:[{key:"a",label:"Getal A",type:"number",default:12},{key:"b",label:"Getal B",type:"number",default:18}], outputs:[{key:"kgv",label:"KGV",format:"number",primary:true}], calc:v=>({kgv:calc.kgv(n(v,"a"),n(v,"b"))}) },
  "ggd-berekenen": { title: "GGD Berekenen", icon: I.Calculator, iconBg: "bg-amber-100 text-amber-600", category: "Wiskunde", description: "Bereken de grootste gemene deler van twee getallen", fields:[{key:"a",label:"Getal A",type:"number",default:24},{key:"b",label:"Getal B",type:"number",default:36}], outputs:[{key:"ggd",label:"GGD",format:"number",primary:true}], calc:v=>({ggd:calc.ggd(n(v,"a"),n(v,"b"))}) },
  "richtingscoefficient": { title: "Richtingscoëfficiënt", icon: I.Calculator, iconBg: "bg-amber-100 text-amber-600", category: "Wiskunde", description: "Bereken de richtingscoëfficiënt en intercept van een lijn door twee punten", fields:[{key:"x1",label:"X₁",type:"number",default:0},{key:"y1",label:"Y₁",type:"number",default:0},{key:"x2",label:"X₂",type:"number",default:2},{key:"y2",label:"Y₂",type:"number",default:4}], outputs:[{key:"rc",label:"Richtingscoëfficiënt",format:"number",primary:true},{key:"intercept",label:"Intercept",format:"number"}], calc:v=>calc.richtingsCoefficient(n(v,"x1"),n(v,"y1"),n(v,"x2"),n(v,"y2")) },
  "afstand-tussen-punten": { title: "Afstand Tussen Punten", icon: I.Calculator, iconBg: "bg-amber-100 text-amber-600", category: "Wiskunde", description: "Bereken de afstand tussen twee punten in een vlak", fields:[{key:"x1",label:"X₁",type:"number",default:0},{key:"y1",label:"Y₁",type:"number",default:0},{key:"x2",label:"X₂",type:"number",default:3},{key:"y2",label:"Y₂",type:"number",default:4}], outputs:[{key:"afstand",label:"Afstand",format:"number",primary:true,suffix:"eenheid"}], calc:v=>({afstand:calc.afstandTussenPunten(n(v,"x1"),n(v,"y1"),n(v,"x2"),n(v,"y2"))}) },
  "driehoek-oppervlakte": { title: "Driehoek Oppervlakte", icon: I.Calculator, iconBg: "bg-amber-100 text-amber-600", category: "Wiskunde", description: "Bereken de oppervlakte van een driehoek (basis × hoogte ÷ 2)", fields:[{key:"basis",label:"Basis",type:"number",default:10},{key:"hoogte",label:"Hoogte",type:"number",default:5}], outputs:[{key:"oppervlakte",label:"Oppervlakte",format:"number",primary:true,suffix:"cm²"}], calc:v=>({oppervlakte:calc.driehoekOppervlakte(n(v,"basis"),n(v,"hoogte"))}) },
  "cirkel-berekenen": { title: "Cirkelberekeningen", icon: I.Calculator, iconBg: "bg-amber-100 text-amber-600", category: "Wiskunde", description: "Bereken omtrek en oppervlakte van een cirkel", fields:[{key:"straal",label:"Straal",type:"number",default:5}], outputs:[{key:"omtrek",label:"Omtrek",format:"number",primary:true,suffix:"cm"},{key:"oppervlakte",label:"Oppervlakte",format:"number",suffix:"cm²"}], calc:v=>calc.cirkelBerekeningen(n(v,"straal")) },

  // ── Algemeen — Datum/Tijd (8) ──
  "leeftijd-berekenen": { title: "Leeftijd Berekenen", icon: I.Clock, iconBg: "bg-slate-100 text-slate-600", category: "Algemeen", description: "Bereken je exacte leeftijd in jaren, maanden en dagen", fields:[{key:"geboorteDatum",label:"Geboortedatum",type:"date",default:"2000-01-01"}], outputs:[{key:"jaren",label:"Jaren",format:"number",primary:true,suffix:"jr"},{key:"maanden",label:"Maanden",format:"number",suffix:"mnd"},{key:"dagen",label:"Dagen",format:"number",suffix:"dg"},{key:"totaalDagen",label:"Totaal dagen",format:"number"}], calc:v=>calc.leeftijdBerekenen(String(v.geboorteDatum)) },
  "datum-verschil": { title: "Datumverschil", icon: I.Clock, iconBg: "bg-slate-100 text-slate-600", category: "Algemeen", description: "Bereken het aantal dagen, weken en maanden tussen twee data", fields:[{key:"datum1",label:"Datum 1",type:"date",default:"2026-01-01"},{key:"datum2",label:"Datum 2",type:"date",default:"2026-12-31"}], outputs:[{key:"dagen",label:"Dagen",format:"number",primary:true},{key:"weken",label:"Weken",format:"number"},{key:"maanden",label:"Maanden",format:"number"}], calc:v=>calc.datumVerschil(String(v.datum1),String(v.datum2)) },
  "datum-optellen": { title: "Datum Optellen", icon: I.Clock, iconBg: "bg-slate-100 text-slate-600", category: "Algemeen", description: "Tel dagen op bij een datum en zie de nieuwe datum", fields:[{key:"datum",label:"Startdatum",type:"date",default:"2026-01-01"},{key:"dagen",label:"Dagen om toe te voegen",type:"number",default:30}], outputs:[{key:"nieuweDatum",label:"Nieuwe datum",format:"text",primary:true}], calc:v=>({nieuweDatum:calc.datumOptellen(String(v.datum),n(v,"dagen"))}) },
  "weeknummer": { title: "Weeknummer", icon: I.Clock, iconBg: "bg-slate-100 text-slate-600", category: "Algemeen", description: "Ontdek het weeknummer van een datum", fields:[{key:"datum",label:"Datum",type:"date",default:"2026-06-15"}], outputs:[{key:"week",label:"Weeknummer",format:"number",primary:true}], calc:v=>({week:calc.weeknummer(String(v.datum))}) },
  "tijdrekenen": { title: "Tijdrekenen", icon: I.Clock, iconBg: "bg-slate-100 text-slate-600", category: "Algemeen", description: "Tel minuten op bij uren en zie het totaal", fields:[{key:"uren",label:"Uren",type:"number",default:8},{key:"minuten",label:"Minuten",type:"number",default:0},{key:"extraMinuten",label:"Extra minuten",type:"number",default:45}], outputs:[{key:"totaalUren",label:"Totaal uren",format:"number",primary:true,suffix:"uur"},{key:"totaalMinuten",label:"Overige minuten",format:"number",suffix:"min"},{key:"dagen",label:"Dagen",format:"number",suffix:"dg"}], calc:v=>calc.tijdrekenen(n(v,"uren"),n(v,"minuten"),n(v,"extraMinuten")) },
  "schrikkeljaar": { title: "Schrikkeljaar Check", icon: I.Clock, iconBg: "bg-slate-100 text-slate-600", category: "Algemeen", description: "Controleer of een jaar een schrikkeljaar is", fields:[{key:"jaar",label:"Jaar",type:"number",default:2026}], outputs:[{key:"isSchrikkel",label:"Is schrikkeljaar?",format:"text",primary:true}], calc:v=>({isSchrikkel:calc.isSchrikkeljaar(n(v,"jaar"))?"Ja":"Nee"}) },
  "dagen-tot-datum": { title: "Dagen tot Datum", icon: I.Clock, iconBg: "bg-slate-100 text-slate-600", category: "Algemeen", description: "Bereken het aantal dagen tot een bepaalde datum", fields:[{key:"datum",label:"Doeldatum",type:"date",default:"2026-12-31"}], outputs:[{key:"dagen",label:"Dagen",format:"number",primary:true}], calc:v=>({dagen:calc.dagenTotDatum(String(v.datum))}) },
  "werkdagen-tellen": { title: "Werkdagen Tellen", icon: I.Clock, iconBg: "bg-slate-100 text-slate-600", category: "Algemeen", description: "Tel het aantal werkdagen (ma-vr) tussen twee data", fields:[{key:"start",label:"Startdatum",type:"date",default:"2026-06-01"},{key:"einde",label:"Einddatum",type:"date",default:"2026-06-30"}], outputs:[{key:"werkdagen",label:"Werkdagen",format:"number",primary:true},{key:"totaal",label:"Totaal dagen",format:"number"}], calc:v=>calc.werkdagenTellen(String(v.start),String(v.einde)) },

  // ── Gezondheid (8) ──
  "bloeddruk": { title: "Bloeddruk Interpreteren", icon: I.Heart, iconBg: "bg-rose-100 text-rose-600", category: "Gezondheid", description: "Interpreteer je bloeddrukwaarden met categorie en advies", fields:[{key:"bovendruk",label:"Bovendruk (systolisch)",type:"number",default:120},{key:"onderdruk",label:"Onderdruk (diastolisch)",type:"number",default:80}], outputs:[{key:"categorie",label:"Categorie",format:"text",primary:true},{key:"advies",label:"Advies",format:"text"}], calc:v=>calc.bloeddrukInterpretatie(n(v,"bovendruk"),n(v,"onderdruk")) },
  "lichaamsvet-percentage": { title: "Lichaamsvet Percentage", icon: I.Heart, iconBg: "bg-rose-100 text-rose-600", category: "Gezondheid", description: "Schat je lichaamsvetpercentage op basis van omtrekmetingen", fields:[{key:"middelomtrek",label:"Middelomtrek (cm)",type:"number",default:80},{key:"nekomtrek",label:"Nekomtrek (cm)",type:"number",default:38},{key:"lengte",label:"Lengte (cm)",type:"number",default:175},{key:"geslacht",label:"Geslacht",type:"select",default:"man",options:[{value:"man",label:"Man"},{value:"vrouw",label:"Vrouw"}]}], outputs:[{key:"result",label:"Lichaamsvet %",format:"number",primary:true,suffix:"%"}], calc:v=>({result:calc.lichaamsvetPercentage(n(v,"middelomtrek"),n(v,"nekomtrek"),n(v,"lengte"),v.geslacht as "man"|"vrouw")}) },
  "waterbehoefte": { title: "Waterbehoefte", icon: I.Heart, iconBg: "bg-rose-100 text-rose-600", category: "Gezondheid", description: "Bereken je dagelijkse waterbehoefte op basis van gewicht", fields:[{key:"gewicht",label:"Gewicht (kg)",type:"number",default:75},{key:"actief",label:"Activiteit",type:"select",default:0,options:[{value:"0",label:"Normaal"},{value:"1",label:"Actief/sportief"}]}], outputs:[{key:"water",label:"Waterbehoefte",format:"number",primary:true,suffix:"ml/dag"}], calc:v=>({water:calc.waterbehoefte(n(v,"gewicht"),String(v.actief)==="1")}) },
  "hardlooppace": { title: "Hardlooppace", icon: I.Heart, iconBg: "bg-rose-100 text-rose-600", category: "Gezondheid", description: "Bereken je hardlooppace op basis van tijd en afstand", fields:[{key:"tijdMinuten",label:"Tijd (minuten)",type:"number",default:30},{key:"afstandKm",label:"Afstand (km)",type:"number",default:5}], outputs:[{key:"pacePerKm",label:"Pace",format:"text",primary:true},{key:"snelheidKmh",label:"Snelheid",format:"number",suffix:"km/u"}], calc:v=>calc.hardlooppace(n(v,"tijdMinuten"),n(v,"afstandKm")) },
  "wandeltempo": { title: "Wandeltempo", icon: I.Heart, iconBg: "bg-rose-100 text-rose-600", category: "Gezondheid", description: "Bereken afstand, snelheid en calorieën op basis van stappen", fields:[{key:"stappen",label:"Aantal stappen",type:"number",default:10000},{key:"tijdMinuten",label:"Tijd (minuten)",type:"number",default:90},{key:"paslengteCm",label:"Paslengte (cm)",type:"number",default:75}], outputs:[{key:"afstandKm",label:"Afstand",format:"number",primary:true,suffix:"km"},{key:"snelheidKmh",label:"Snelheid",format:"number",suffix:"km/u"},{key:"kcal",label:"Calorieën",format:"number",suffix:"kcal"}], calc:v=>calc.wandeltempo(n(v,"stappen"),n(v,"tijdMinuten"),n(v,"paslengteCm")) },
  "ideale-lengte-kind": { title: "Ideale Lengte Kind", icon: I.Heart, iconBg: "bg-rose-100 text-rose-600", category: "Gezondheid", description: "Bekijk de gemiddelde lengte voor een kind op basis van leeftijd", fields:[{key:"leeftijdMaanden",label:"Leeftijd (maanden)",type:"number",default:24,min:0,max:30},{key:"geslacht",label:"Geslacht",type:"select",default:"jongen",options:[{value:"jongen",label:"Jongen"},{value:"meisje",label:"Meisje"}]}], outputs:[{key:"gemiddeldCm",label:"Gemiddelde lengte",format:"number",primary:true,suffix:"cm"},{key:"range",label:"Normaal bereik",format:"text"}], calc:v=>calc.idealeLengteKind(n(v,"leeftijdMaanden"),v.geslacht as "jongen"|"meisje") },
  "calorie-verbruik-activiteit": { title: "Calorieverbruik per Activiteit", icon: I.Heart, iconBg: "bg-rose-100 text-rose-600", category: "Gezondheid", description: "Bereken je calorieverbruik op basis van gewicht, activiteit en duur", fields:[{key:"gewicht",label:"Gewicht (kg)",type:"number",default:75},{key:"metWaarde",label:"Activiteit (MET)",type:"number",default:8,step:0.5},{key:"minuten",label:"Duur (minuten)",type:"number",default:30}], outputs:[{key:"kcal",label:"Verbrande calorieën",format:"number",primary:true,suffix:"kcal"}], calc:v=>({kcal:calc.calorieVerbruikActiviteit(n(v,"gewicht"),n(v,"metWaarde"),n(v,"minuten"))}) },
  "fietsvermogen": { title: "Fietsvermogen", icon: I.Heart, iconBg: "bg-rose-100 text-rose-600", category: "Gezondheid", description: "Bereken het benodigde fietsvermogen op basis van helling en snelheid", fields:[{key:"gewicht",label:"Gewicht (kg)",type:"number",default:80},{key:"hellingPct",label:"Helling (%)",type:"number",default:2},{key:"snelheidKmh",label:"Snelheid (km/u)",type:"number",default:25},{key:"windTegen",label:"Wind",type:"select",default:"0",options:[{value:"0",label:"Geen wind"},{value:"1",label:"Tegenwind"}]}], outputs:[{key:"vermogen",label:"Vermogen",format:"number",primary:true,suffix:"W"}], calc:v=>({vermogen:calc.fietsVermogen(n(v,"gewicht"),n(v,"hellingPct"),n(v,"snelheidKmh"),String(v.windTegen)==="1")}) },

  // ── Werk & Inkomen (8) ──
  "overuren": { title: "Overuren Berekenen", icon: I.TrendingUp, iconBg: "bg-emerald-100 text-emerald-600", category: "Werk & Inkomen", description: "Bereken de vergoeding voor overuren op basis van je uurloon", fields:[{key:"maandSalaris",label:"Maandsalaris (€)",type:"number",default:3500},{key:"contractUren",label:"Contracturen p/week",type:"number",default:40,min:0,max:40},{key:"overuren",label:"Overuren",type:"number",default:5},{key:"factor",label:"Toeslagfactor",type:"select",default:"1.5",options:[{value:"1",label:"100% (normaal)"},{value:"1.33",label:"133% (gebruikelijk)"},{value:"1.5",label:"150% (overuren)"},{value:"2",label:"200% (feestdag)"}]}], outputs:[{key:"uurloon",label:"Uurloon",format:"eur",primary:true},{key:"overuurToeslag",label:"Toeslag",format:"eur"},{key:"totaal",label:"Totaal vergoeding",format:"eur"}], calc:v=>calc.overurenBetalen(n(v,"maandSalaris"),n(v,"contractUren"),n(v,"overuren"),Number(v.factor)) },
  "reiskosten-woonwerk": { title: "Reiskosten Woon-Werk", icon: I.TrendingUp, iconBg: "bg-emerald-100 text-emerald-600", category: "Werk & Inkomen", description: "Bereken je reiskostenvergoeding op basis van afstand en dagen", fields:[{key:"afstandEnkeleReis",label:"Afstand enkele reis (km)",type:"number",default:25},{key:"dagenPerWeek",label:"Dagen per week",type:"number",default:4,min:0,max:5},{key:"vergoedingPerKm",label:"Vergoeding per km (€)",type:"number",default:0.23,step:0.01}], outputs:[{key:"maand",label:"Per maand",format:"eur",primary:true},{key:"jaar",label:"Per jaar",format:"eur"}], calc:v=>calc.reiskostenWoonWerk(n(v,"afstandEnkeleReis"),n(v,"dagenPerWeek"),n(v,"vergoedingPerKm")) },
  "thuiswerkvergoeding": { title: "Thuiswerkvergoeding", icon: I.TrendingUp, iconBg: "bg-emerald-100 text-emerald-600", category: "Werk & Inkomen", description: "Bereken de totale thuiswerkvergoeding op basis van dagen en tarief", fields:[{key:"dagenPerWeek",label:"Dagen thuis per week",type:"number",default:2,min:0,max:5},{key:"vergoedingPerDag",label:"Vergoeding per dag (€)",type:"number",default:2.15,step:0.05}], outputs:[{key:"maand",label:"Per maand",format:"eur",primary:true},{key:"jaar",label:"Per jaar",format:"eur"}], calc:v=>calc.thuiswerkVergoeding(n(v,"dagenPerWeek"),n(v,"vergoedingPerDag")) },
  "eindejaarsuitkering": { title: "Eindejaarsuitkering", icon: I.TrendingUp, iconBg: "bg-emerald-100 text-emerald-600", category: "Werk & Inkomen", description: "Bereken bruto en netto eindejaarsuitkering", fields:[{key:"jaarSalaris",label:"Jaarsalaris (€)",type:"number",default:50000},{key:"pct",label:"Uitkeringspercentage",type:"number",default:8.33,step:0.01}], outputs:[{key:"bruto",label:"Bruto",format:"eur",primary:true},{key:"netto",label:"Netto (indicatie)",format:"eur"}], calc:v=>calc.eindejaarsuitkering(n(v,"jaarSalaris"),n(v,"pct")) },
  "dertiende-maand": { title: "Dertiende Maand", icon: I.TrendingUp, iconBg: "bg-emerald-100 text-emerald-600", category: "Werk & Inkomen", description: "Bereken de bruto en netto dertiende maand", fields:[{key:"maandSalaris",label:"Maandsalaris (€)",type:"number",default:3500}], outputs:[{key:"bruto",label:"Bruto",format:"eur",primary:true},{key:"netto",label:"Netto (indicatie)",format:"eur"}], calc:v=>calc.dertiendeMaand(n(v,"maandSalaris")) },
  "bonus-netto": { title: "Bonus Netto Berekenen", icon: I.TrendingUp, iconBg: "bg-emerald-100 text-emerald-600", category: "Werk & Inkomen", description: "Bereken wat je netto overhoudt van je bonus", fields:[{key:"bonusBruto",label:"Bonus bruto (€)",type:"number",default:5000},{key:"jaarInkomen",label:"Jaarinkomen (€)",type:"number",default:50000}], outputs:[{key:"netto",label:"Netto",format:"eur",primary:true},{key:"belasting",label:"Belasting",format:"eur"},{key:"bijzonderTarief",label:"Bijzonder tarief",format:"pct"}], calc:v=>calc.bonusNetto(n(v,"bonusBruto"),n(v,"jaarInkomen")) },
  "ziektewet-uitkering": { title: "Ziektewet Uitkering", icon: I.TrendingUp, iconBg: "bg-emerald-100 text-emerald-600", category: "Werk & Inkomen", description: "Bereken de hoogte van je ziektewetuitkering", fields:[{key:"maandSalaris",label:"Maandsalaris (€)",type:"number",default:3500}], outputs:[{key:"brutoPerMaand",label:"Uitkering per maand",format:"eur",primary:true},{key:"percentage",label:"Percentage",format:"pct"}], calc:v=>calc.ziektewetUitkering(n(v,"maandSalaris")) },
  "ww-uitkering": { title: "WW-Uitkering Schatting", icon: I.TrendingUp, iconBg: "bg-emerald-100 text-emerald-600", category: "Werk & Inkomen", description: "Schat je WW-uitkering op basis van salaris en dienstjaren", fields:[{key:"maandSalaris",label:"Maandsalaris (€)",type:"number",default:3500},{key:"dienstjaren",label:"Dienstjaren",type:"number",default:5},{key:"werkloosWeken",label:"Weken al werkloos",type:"number",default:0}], outputs:[{key:"maximaal",label:"Max. uitkering p/mnd",format:"eur",primary:true},{key:"resterendWeken",label:"Resterende weken",format:"number",suffix:"wkn"}], calc:v=>calc.wwUitkeringSchatting(n(v,"maandSalaris"),n(v,"dienstjaren"),n(v,"werkloosWeken")) },

  // ── Ondernemen (7) ──
  "break-even-analyse": { title: "Break-Even Analyse", icon: I.TrendingUp, iconBg: "bg-blue-100 text-indigo-600", category: "Ondernemen", description: "Bereken hoeveel eenheden je moet verkopen om quitte te draaien", fields:[{key:"vasteKosten",label:"Vaste kosten (€)",type:"number",default:50000},{key:"verkoopPrijs",label:"Verkoopprijs per stuk (€)",type:"number",default:100},{key:"variabeleKostenPerStuk",label:"Variabele kosten per stuk (€)",type:"number",default:40}], outputs:[{key:"eenheden",label:"Minimale eenheden",format:"number",primary:true},{key:"omzet",label:"Minimale omzet",format:"eur"}], calc:v=>calc.breakEvenAnalyse(n(v,"vasteKosten"),n(v,"verkoopPrijs"),n(v,"variabeleKostenPerStuk")) },
  "costplus-prijs": { title: "Cost-Plus Prijs", icon: I.TrendingUp, iconBg: "bg-blue-100 text-indigo-600", category: "Ondernemen", description: "Bereken de verkoopprijs op basis van kostprijs en marge", fields:[{key:"kostprijs",label:"Kostprijs (€)",type:"number",default:50},{key:"margePct",label:"Marge (%)",type:"number",default:30}], outputs:[{key:"verkoopprijs",label:"Verkoopprijs",format:"eur",primary:true},{key:"winst",label:"Winst per stuk",format:"eur"}], calc:v=>calc.costPlusPrijs(n(v,"kostprijs"),n(v,"margePct")) },
  "krediettermijn": { title: "Krediettermijn", icon: I.TrendingUp, iconBg: "bg-blue-100 text-indigo-600", category: "Ondernemen", description: "Bereken de looptijd van een openstaande vordering", fields:[{key:"vordering",label:"Openstaand bedrag (€)",type:"number",default:12000},{key:"maandelijkseBetaling",label:"Maandelijkse betaling (€)",type:"number",default:1000}], outputs:[{key:"maanden",label:"Looptijd",format:"number",primary:true,suffix:"mnd"}], calc:v=>calc.krediettermijn(n(v,"vordering"),n(v,"maandelijkseBetaling")) },
  "btw-privegebruik": { title: "BTW Privégebruik", icon: I.TrendingUp, iconBg: "bg-blue-100 text-indigo-600", category: "Ondernemen", description: "Bereken BTW-correctie voor privégebruik van zakelijke goederen", fields:[{key:"materiaal",label:"Materiaalkosten (€)",type:"number",default:500},{key:"uren",label:"Uren besteed",type:"number",default:10},{key:"uurtarief",label:"Uurtarief (€)",type:"number",default:75},{key:"btwPct",label:"BTW-tarief (%)",type:"number",default:21}], outputs:[{key:"correctie",label:"BTW-correctie",format:"eur",primary:true},{key:"totaal",label:"Totaal incl. BTW",format:"eur"}], calc:v=>calc.btwPriveGebruik(n(v,"materiaal"),n(v,"uren"),n(v,"uurtarief"),n(v,"btwPct")) },
  "autokosten-bijtelling": { title: "Autokosten Bijtelling", icon: I.TrendingUp, iconBg: "bg-blue-100 text-indigo-600", category: "Ondernemen", description: "Bereken de bijtelling voor een auto van de zaak", fields:[{key:"catalogusPrijs",label:"Catalogusprijs (€)",type:"number",default:45000},{key:"bijtellingPct",label:"Bijtelling (%)",type:"number",default:22},{key:"eigenBijdrageMaand",label:"Eigen bijdrage p/mnd (€)",type:"number",default:0}], outputs:[{key:"bijtellingJaar",label:"Bijtelling per jaar",format:"eur",primary:true},{key:"bijtellingMaand",label:"Per maand",format:"eur"},{key:"nettoPerMaand",label:"Netto per maand",format:"eur"}], calc:v=>calc.autokostenBijtelling(n(v,"catalogusPrijs"),n(v,"bijtellingPct"),n(v,"eigenBijdrageMaand")) },
  "vof-winstverdeling": { title: "VOF Winstverdeling", icon: I.TrendingUp, iconBg: "bg-blue-100 text-indigo-600", category: "Ondernemen", description: "Verdeel de winst in een VOF op basis van investeringsaandeel", fields:[{key:"winst",label:"Totale winst (€)",type:"number",default:100000},{key:"aandeelA",label:"Aandeel vennot A (€)",type:"number",default:60000},{key:"aandeelB",label:"Aandeel vennot B (€)",type:"number",default:40000}], outputs:[{key:"a",label:"Vennot A ontvangt",format:"eur",primary:true},{key:"b",label:"Vennot B ontvangt",format:"eur"},{key:"pctA",label:"Aandeel A",format:"pct"},{key:"pctB",label:"Aandeel B",format:"pct"}], calc:v=>calc.vofWinstverdeling(n(v,"winst"),n(v,"aandeelA"),n(v,"aandeelB")) },
  "uurtarief-kostprijs": { title: "Uurtarief Kostprijs", icon: I.TrendingUp, iconBg: "bg-blue-100 text-indigo-600", category: "Ondernemen", description: "Bereken je minimale uurtarief op basis van gewenst inkomen", fields:[{key:"gewenstNettoMaand",label:"Gewenst netto inkomen p/m (€)",type:"number",default:4000},{key:"werkdagenPerMaand",label:"Werkdagen per maand",type:"number",default:20},{key:"urenPerDag",label:"Uren per dag",type:"number",default:8},{key:"overheadPct",label:"Overhead (%)",type:"number",default:30}], outputs:[{key:"tariefExcl",label:"Tarief excl. BTW",format:"eur",primary:true},{key:"tariefIncl",label:"Tarief incl. BTW",format:"eur"},{key:"dekking",label:"Dekkingsbijdrage",format:"eur"}], calc:v=>calc.uurtariefKostprijs(n(v,"gewenstNettoMaand"),n(v,"werkdagenPerMaand"),n(v,"urenPerDag"),n(v,"overheadPct")) },

  // ── Geld & Verzekeringen (9) ──
  "spaardoel-berekenen": { title: "Spaardoel Berekenen", icon: I.PiggyBank, iconBg: "bg-violet-100 text-violet-600", category: "Geld & Verzekeringen", description: "Bereken de eindwaarde van sparen met maandelijkse inleg", fields:[{key:"startkapitaal",label:"Startkapitaal (€)",type:"number",default:5000},{key:"maandelijkseInleg",label:"Maandelijkse inleg (€)",type:"number",default:200},{key:"rentePct",label:"Rente (%)",type:"number",default:2,step:0.1},{key:"maanden",label:"Looptijd (maanden)",type:"number",default:60}], outputs:[{key:"eindbedrag",label:"Eindbedrag",format:"eur",primary:true},{key:"totaalInleg",label:"Totaal ingelegd",format:"eur"},{key:"totaalRente",label:"Totaal rente",format:"eur"}], calc:v=>calc.spaardoelBerekenen(n(v,"startkapitaal"),n(v,"maandelijkseInleg"),n(v,"rentePct"),n(v,"maanden")) },
  "lineaire-aflossing": { title: "Lineaire Aflossing", icon: I.PiggyBank, iconBg: "bg-violet-100 text-violet-600", category: "Geld & Verzekeringen", description: "Bereken de maandlasten bij lineaire hypotheek/aflossing", fields:[{key:"lening",label:"Lening (€)",type:"number",default:250000},{key:"looptijdMaanden",label:"Looptijd (maanden)",type:"number",default:360},{key:"rentePct",label:"Rente (%)",type:"number",default:4,step:0.1}], outputs:[{key:"maandLastenEerste",label:"Eerste maand",format:"eur",primary:true},{key:"maandLastenLaatste",label:"Laatste maand",format:"eur"},{key:"totaleRente",label:"Totale rente",format:"eur"},{key:"totaal",label:"Totaal betaald",format:"eur"}], calc:v=>calc.lineaireAflossing(n(v,"lening"),n(v,"looptijdMaanden"),n(v,"rentePct")) },
  "studieschuld-terugbetalen": { title: "Studieschuld Terugbetalen", icon: I.PiggyBank, iconBg: "bg-violet-100 text-violet-600", category: "Geld & Verzekeringen", description: "Bereken de maandelijkse aflossing van je studieschuld", fields:[{key:"schuld",label:"Studieschuld (€)",type:"number",default:30000},{key:"draagkrachtMaand",label:"Draagkracht p/mnd (€)",type:"number",default:200},{key:"rentePct",label:"Rente (%)",type:"number",default:2.56,step:0.01}], outputs:[{key:"maandBedrag",label:"Maandbedrag",format:"eur",primary:true},{key:"looptijdMaanden",label:"Looptijd",format:"number",suffix:"mnd"},{key:"totaal",label:"Totaal terugbetaald",format:"eur"}], calc:v=>calc.studieschuldTerugbetalen(n(v,"schuld"),n(v,"draagkrachtMaand"),n(v,"rentePct")) },
  "eigen-risico-zorg": { title: "Eigen Risico Zorg", icon: I.PiggyBank, iconBg: "bg-violet-100 text-violet-600", category: "Geld & Verzekeringen", description: "Bereken hoeveel zorgkosten je zelf betaalt met eigen risico", fields:[{key:"zorgKosten",label:"Zorgkosten (€)",type:"number",default:1500},{key:"eigenRisico",label:"Eigen risico (€)",type:"number",default:385}], outputs:[{key:"zelfBetalen",label:"Zelf betalen",format:"eur",primary:true},{key:"vergoeding",label:"Vergoeding",format:"eur"},{key:"resterendEigenRisico",label:"Resterend eigen risico",format:"eur"}], calc:v=>calc.eigenRisicoZorg(n(v,"zorgKosten"),n(v,"eigenRisico")) },
  "verhuiskosten": { title: "Verhuiskosten Berekenen", icon: I.PiggyBank, iconBg: "bg-violet-100 text-violet-600", category: "Geld & Verzekeringen", description: "Bereken de totale kosten van een verhuizing en terugverdientijd", fields:[{key:"huidigeHuur",label:"Huidige huur (€)",type:"number",default:1200},{key:"nieuweHuur",label:"Nieuwe huur (€)",type:"number",default:1400},{key:"overbruggingMaanden",label:"Overbrugging (maanden)",type:"number",default:1},{key:"verhuisBedrag",label:"Verhuiskosten (€)",type:"number",default:3000}], outputs:[{key:"totaleKosten",label:"Totale kosten",format:"eur",primary:true},{key:"maandelijkseBesparing",label:"Maandelijkse besparing",format:"eur"},{key:"terugverdienMaanden",label:"Terugverdientijd",format:"number",suffix:"mnd"}], calc:v=>calc.verhuisKosten(n(v,"huidigeHuur"),n(v,"nieuweHuur"),n(v,"overbruggingMaanden"),n(v,"verhuisBedrag")) },
  "overwaarde-berekenen": { title: "Overwaarde Berekenen", icon: I.PiggyBank, iconBg: "bg-violet-100 text-violet-600", category: "Geld & Verzekeringen", description: "Bereken de overwaarde van je woning na verkoop", fields:[{key:"huidigeWaarde",label:"Huidige waarde (€)",type:"number",default:400000},{key:"hypotheekSaldo",label:"Hypotheeksaldo (€)",type:"number",default:200000},{key:"verkoopKostenPct",label:"Verkoopkosten (%)",type:"number",default:2}], outputs:[{key:"overwaarde",label:"Overwaarde",format:"eur",primary:true},{key:"nettoOpbrengst",label:"Netto opbrengst",format:"eur"},{key:"kosten",label:"Kosten",format:"eur"}], calc:v=>calc.overwaardeBerekenen(n(v,"huidigeWaarde"),n(v,"hypotheekSaldo"),n(v,"verkoopKostenPct")) },
  "huurverhoging": { title: "Huurverhoging Berekenen", icon: I.PiggyBank, iconBg: "bg-violet-100 text-violet-600", category: "Geld & Verzekeringen", description: "Bereken de nieuwe huur na een huurverhoging (max 5,5% in 2026)", fields:[{key:"huidigeHuur",label:"Huidige huur (€)",type:"number",default:800},{key:"verhogingPct",label:"Voorgestelde verhoging (%)",type:"number",default:5.5}], outputs:[{key:"nieuweHuur",label:"Nieuwe huur",format:"eur",primary:true},{key:"stijging",label:"Stijging",format:"eur"},{key:"max2026",label:"Max. in 2026",format:"pct"}], calc:v=>calc.huurverhogingBerekenen(n(v,"huidigeHuur"),n(v,"verhogingPct")) },
  "enkelvoudige-interest": { title: "Enkelvoudige Interest", icon: I.PiggyBank, iconBg: "bg-violet-100 text-violet-600", category: "Geld & Verzekeringen", description: "Bereken enkelvoudige interest over een hoofdsom", fields:[{key:"hoofdsom",label:"Hoofdsom (€)",type:"number",default:10000},{key:"rentePct",label:"Rente (%)",type:"number",default:3,step:0.1},{key:"jaren",label:"Jaren",type:"number",default:5}], outputs:[{key:"totaal",label:"Eindbedrag",format:"eur",primary:true},{key:"rente",label:"Totale rente",format:"eur"}], calc:v=>calc.enkelvoudigeInterest(n(v,"hoofdsom"),n(v,"rentePct"),n(v,"jaren")) },
  "vermogensbelasting-box3": { title: "Vermogensbelasting Box 3", icon: I.PiggyBank, iconBg: "bg-violet-100 text-violet-600", category: "Geld & Verzekeringen", description: "Bereken de Box 3 belasting over je vermogen", fields:[{key:"vermogen",label:"Spaargeld + beleggingen (€)",type:"number",default:150000},{key:"schulden",label:"Schulden (€)",type:"number",default:20000},{key:"heffingsvrijVermogen",label:"Heffingsvrij vermogen (€)",type:"number",default:57000}], outputs:[{key:"grondslag",label:"Grondslag",format:"eur",primary:true},{key:"rendement",label:"Forfaitair rendement",format:"eur"},{key:"belasting",label:"Belasting 36%",format:"eur"}], calc:v=>calc.vermogensBelastingBox3(n(v,"vermogen"),n(v,"schulden"),n(v,"heffingsvrijVermogen")) },
};
