import type { Metadata } from "next"; import { Container } from "@/components/ui/Container"; import { HelpCircle, ChevronRight } from "lucide-react";
export const metadata: Metadata = { title: "Veelgestelde Vragen — Rekenhet.nl", description: "Antwoorden op de meest gestelde vragen over Rekenhet.nl. Hoe werken de calculators, zijn ze gratis en hoe actueel zijn de tarieven?" };
const FAQS = [
  { q: "Zijn alle calculators op Rekenhet.nl gratis?", a: "Ja, alle calculators zijn volledig gratis. Je hebt geen account nodig en kunt onbeperkt berekeningen maken." },
  { q: "Hoe actueel zijn de belastingtarieven?", a: "Alle tarieven worden maandelijks bijgewerkt op basis van de laatste wetgeving van de Belastingdienst en SVB." },
  { q: "Kan ik de resultaten opslaan of delen?", a: "Ja, je kunt resultaten kopiëren, delen via e-mail, downloaden als PDF of een deelbare link genereren." },
  { q: "Hoe nauwkeurig zijn de berekeningen?", a: "De berekeningen zijn gebaseerd op officiële bronnen (Belastingdienst, SVB, RVO, CBS). Het blijven indicaties. Raadpleeg een professional voor definitief advies." },
  { q: "Worden er cookies gebruikt?", a: "Ja, voor de werking van de site en optioneel voor advertenties. Je kunt zelf kiezen of je advertentie-cookies accepteert via de cookiebanner." },
  { q: "Kan ik een calculator missen?", a: "Laat het ons weten via de contactpagina. We voegen regelmatig nieuwe calculators toe op basis van gebruikersverzoeken." },
];
export default function FaqPage() { return (<Container className="py-8 max-w-3xl"><h1 className="text-3xl font-bold text-gray-900 mb-2">Veelgestelde vragen</h1><p className="text-gray-500 mb-8">Antwoorden op de meest gestelde vragen over Rekenhet.nl.</p><div className="space-y-3">{FAQS.map((f,i)=><details key={i} className="group rounded-xl border border-gray-200 bg-white shadow-sm open:border-indigo-200 transition-all"><summary className="flex cursor-pointer items-center justify-between px-5 py-4 text-sm font-medium text-gray-700 hover:text-indigo-600"><span className="flex items-center gap-2"><HelpCircle className="h-4 w-4 text-indigo-500 shrink-0"/>{f.q}</span><ChevronRight className="h-4 w-4 text-gray-400 transition-transform group-open:rotate-90"/></summary><div className="px-5 pb-5 border-t border-gray-100 pt-3"><p className="text-sm text-gray-600 leading-relaxed">{f.a}</p></div></details>)}</div></Container>);}
